# Generated by Django 4.2.29 on 2026-04-11 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
                ('emoji', models.CharField(default='💬', max_length=10, verbose_name='Эмодзи')),
                ('url', models.URLField(verbose_name='Ссылка на группу')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Группа поддержки (Web)',
                'verbose_name_plural': 'Группы поддержки (Web)',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('problem', models.TextField(verbose_name='Описание проблемы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Запрос пользователя (Web)',
                'verbose_name_plural': 'Запросы пользователей (Web)',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WebSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование специализации')),
                ('icon', models.CharField(blank=True, default='🧠', max_length=10, verbose_name='Эмодзи иконка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Специализация (Web)',
                'verbose_name_plural': 'Специализации (Web)',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('session_token', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Токен сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Пользователь (Web)',
                'verbose_name_plural': 'Пользователи (Web)',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WebSpecialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='specialists/', verbose_name='Фото')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена за сеанс (руб.)')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Рейтинг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_online', models.BooleanField(default=False, verbose_name='Онлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialists', to='webtgbot.webspecialization', verbose_name='Специализация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='web_specialist', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь Django')),
            ],
            options={
                'verbose_name': 'Специалист (Web)',
                'verbose_name_plural': 'Специалисты (Web)',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало сессии')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает в')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена в')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='webtgbot.webuser', verbose_name='Клиент')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='webtgbot.webspecialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Сессия чата (Web)',
                'verbose_name_plural': 'Сессии чатов (Web)',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('client', 'Клиент'), ('specialist', 'Специалист')], max_length=20, verbose_name='Тип отправителя')),
                ('message_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('audio', 'Аудио'), ('voice', 'Голосовое'), ('sticker', 'Стикер'), ('file', 'Файл')], default='text', max_length=20, verbose_name='Тип сообщения')),
                ('content', models.TextField(blank=True, default='', verbose_name='Содержимое')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat_media/%Y/%m/%d/', verbose_name='Файл')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='webtgbot.chatsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Сообщение (Web)',
                'verbose_name_plural': 'Сообщения (Web)',
                'ordering': ('created_at',),
            },
        ),
    ]
