# Generated by Django 4.2.29 on 2026-04-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtgbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportgroup',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='webspecialization',
            name='icon',
        ),
        migrations.AddField(
            model_name='webspecialist',
            name='telegram_id',
            field=models.IntegerField(blank=True, help_text='Укажите Telegram ID специалиста для получения уведомлений', null=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Истекает в'),
        ),
        migrations.AlterField(
            model_name='supportgroup',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='webspecialization',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Порядок'),
        ),
    ]
