# Generated by Django 4.2.29 on 2026-04-16 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_specialist_client_alter_client_specialist_and_more'),
        ('webtgbot', '0002_remove_supportgroup_emoji_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_sessions', to='tgbot.specialist', verbose_name='Специалист'),
        ),
        migrations.DeleteModel(
            name='WebSpecialist',
        ),
        migrations.DeleteModel(
            name='WebSpecialization',
        ),
    ]
