# Generated by Django 4.2.29 on 2026-04-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtgbot', '0003_alter_chatsession_specialist_delete_webspecialist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактные данные'),
        ),
    ]
