# Generated by Django 5.0.2 on 2026-07-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtgbot', '0004_userrequest_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='cleaned',
            field=models.BooleanField(default=False, verbose_name='Xabarlar tozalangan'),
        ),
    ]
