# Generated by Django 5.0.2 on 2026-07-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtgbot', '0005_chatsession_cleaned'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP адрес')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Bloklash sababi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Bloklangan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Bloklangan IP',
                'verbose_name_plural': 'Bloklangan IP lar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='webuser',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес'),
        ),
    ]
