# Generated by Django 5.0.2 on 2024-02-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='avatar_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL аватара'),
        ),
    ]
