# Generated by Django 5.0.2 on 2024-02-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_telegramuser_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Токен'),
        ),
    ]
