# Generated by Django 5.0.2 on 2024-02-26 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_client_name_specialist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSpecialistRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Активная связь')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_relations', to='tgbot.client', verbose_name='Клиент')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_relations', to='tgbot.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Связь Клиент-Специалист',
                'verbose_name_plural': 'Связи Клиент-Специалист',
                'ordering': ('-start_time',),
            },
        ),
    ]
