# Generated by Django 5.0.3 on 2024-05-24 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_clientspecialistrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_specialist', to='tgbot.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='client',
            name='specialist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialist_client', to='tgbot.specialist', verbose_name='Специалист'),
        ),
        migrations.DeleteModel(
            name='ClientSpecialistRelation',
        ),
    ]
