# Generated by Django 4.2.29 on 2026-04-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_specialist_client_alter_client_specialist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_used_free_session',
            field=models.BooleanField(default=False, verbose_name='Использовал бесплатную сессию'),
        ),
    ]
